filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

output.elasticsearch:
  hosts: ["https://elasticsearch1:9200"]
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]